name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * 1'  # Run every Monday at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Update dependencies
        run: |
          npm update
      
      - name: Check for outdated packages
        id: outdated
        run: |
          npm outdated || true
          echo "outdatedCount=$(npm outdated --json | jq 'length')" >> $GITHUB_OUTPUT
        
      - name: Create Pull Request
        if: steps.outdated.outputs.outdatedCount != '0'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(deps): update dependencies"
          title: "chore(deps): update dependencies"
          body: |
            This PR updates project dependencies to their latest versions.
            
            Auto-generated by the Dependency Updates workflow.
          branch: dependency-updates
          base: dev
          labels: dependencies
          
      - name: Notify on Slack
        if: steps.outdated.outputs.outdatedCount != '0'
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "📦 Dependency update pull request created",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "📦 *Dependency update pull request created*"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Check the PR for details."
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
